services:
  mariadb:
    build: ./mariadb
    image: mariadb
    container_name: mariadb
    expose:
      - 3306
    env_file:
      - .env
    volumes:
      - mariadb:/var/list/mysql
    networks:
      - inception
#   wordpress:
#     image: wordpress
#     container_name: wordpress
#     build: ./requirements/wordpress